/*
 * [bud].[CreateBudgetWithSubBudgets] — LIVE definition, supplied 2026-09-24.
 * Source: sys.sql_modules.definition, copied from an SSMS results grid.
 *
 * The grid collapsed every line break into spaces, so the definition below is
 * the original text on ONE line, otherwise verbatim. Read it; do not run it —
 * the first `--` comment would comment out everything after it. For a runnable
 * copy use SSMS Tasks > Generate Scripts.
 */
  -- Comprehensive Procedure to Create Budget with Sub-Budgets (Updated)  CREATE PROCEDURE [bud].[CreateBudgetWithSubBudgets]      @company INT,      @budgetName NVARCHAR(255),      @description NVARCHAR(MAX) = NULL,      @totalAmount DECIMAL(15, 2) = 0.00,      @isActive BIT = 1,      @subBudgets bud.SubBudgetTableType READONLY,      @newBudgetId INT OUTPUT  AS  BEGIN      SET NOCOUNT ON;            BEGIN TRY          BEGIN TRANSACTION;                    -- Step 1: Create the Budget          INSERT INTO bud.Budgets (company, budgetName, description, totalAmount, isActive)          VALUES (@company, @budgetName, @description, @totalAmount, @isActive);                    -- Get the newly created budget ID          SET @newBudgetId = SCOPE_IDENTITY();                    -- Step 2: Create Sub-Budgets if any are provided          IF EXISTS (SELECT 1 FROM @subBudgets)          BEGIN              INSERT INTO bud.SubBudgets (budgetId, subBudgetName, description, isActive)              SELECT                   @newBudgetId,                  subBudgetName,                  description,                  1 -- isActive = true by default              FROM @subBudgets;          END                    COMMIT TRANSACTION;                    -- Return success message with budget details          SELECT               @newBudgetId AS budgetId,              @budgetName AS budgetName,              @company AS companyId,              'Budget and Sub-Budgets created successfully' AS message,              (SELECT COUNT(*) FROM @subBudgets) AS subBudgetsCreated;                    END TRY      BEGIN CATCH          IF @@TRANCOUNT > 0              ROLLBACK TRANSACTION;                        -- Return error details          DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();          DECLARE @ErrorSeverity INT = ERROR_SEVERITY();          DECLARE @ErrorState INT = ERROR_STATE();                    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);      END CATCH  END
